#!/bin/bash
DIR=/home/pi/captive-portal
NODE=/usr/local/bin/node

test -x $NODE || exit 0

function start_app {
        NODE_ENV=production NODE_DIR="$DIR" nohup "$NODE" "$DIR/app.js" 1>>"/var/log/captive-portal.log" 2>&1 & echo $! > "/run/captive-portal.pid"
}

function stop_app {
  sudo kill `/run/captive-portal.pid`
}

case $1 in
   start)
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: captive-portal {start|stop}" ;;
esac
exit 0
